<?php

$config['moduleList'] = array(
	'administrator' => 'Full Administrator',
	'login' => 'Login Akses',
	'purchasing' => 'Purchasing',
	'inventory' => 'Inventory',
	'sales' => 'Sales',
	'finance' => 'Finance and Accounting',
	'master' => 'Data Master',
	'myuser' =>  'User Management'
);
$config['controllerList'] = array(
	'purchasing_agingUtang' => 'Set Aging Hutang',
	'purchasing_purchaseOrder' => 'Purchase Order',
	'purchasing_invoice' => 'Invoice',
	'purchasing_barangDiterima' => 'Penerimaan Barang',
	'purchasing_purchasingDebitNote' => 'Debit Note',

	'inventory_persediaan' => 'Persediaan',
	'inventory_inventorySummary' => 'Stok Persediaan',
	'inventory_stockAdjustment' => 'Penyesuaian Stok',
	'inventory_transferGudang' => 'Transfer Gudang',
	'inventory_inventoryDebitNote' => 'Retur Debit Note',

	'finance_asset' => 'Fix Asset',
	'finance_budgetCost' => 'Budget Cost',
	'finance_budgetPurchasing' => 'Budget Purchasing',
	'finance_bukuBesar' => 'Buku Besar',
	'finance_cekGiro' => 'Cek Giro',
	'finance_currentSaldo' => 'Saldo Saat Ini',
	'finance_fakturPajakCustomer' => 'Faktur Pajak Customer',
	'finance_fakturPajakSuplier' => 'Faktur Pajak Supplier',
	'finance_returFakturCustomer' => 'Retur Faktur Pajak Customer',
	'finance_returFakturSuplier' => 'Retur Faktur Pajak Supplier',
	'finance_hpp' => 'Hpp',
	'finance_jurnal' => 'Jurnal',
	'finance_jurnalPenyesuaian' => 'Jurnal Penyesuaian',
	'finance_kasBank' => 'Kas Bank',    
	'finance_laporanKasBank' => 'Laporan Kas Bank',
	'finance_laporanKeuangan' => 'Laporan Keuangan',
	'finance_laporanNeraca' => 'Laporan Neraca',	
	'finance_mutasi' => 'Mutasi',
	'finance_neraca' => 'Neraca',
	'finance_neracaLajur' => 'Lajur Neraca',
	'finance_pembayaranHutang' => 'Pembayaran Hutang',
	'finance_penagihanPiutang' => 'Penagihan Piutang',
	'finance_penerimaanPiutang' => 'Penerimaan Piutang',
	'finance_pengeluarankasBank' => 'Pengeluaran Kas Bank',
	'finance_penyesuaianHutang' => 'Penyesuaian Hutang',
	'finance_penyesuaianPiutang' => 'Penyesuaian Piutang',
	'finance_perubahanModal' => 'Perubahan Modal',
	'finance_receiveMoney' => 'Penerimaan Uang',
	'finance_report' => 'Report',
	'finance_spendMoney' => 'Spend Money',
	'finance_transaksi' => 'Transaksi',
	'finance_transaksiCustomer' => 'Transaksi Customer',

	'sales_penawaran' => 'Penawaran',
	'sales_poCustomer' => 'Sales Order',
	'sales_suratJalan' => 'Surat Jalan',
	'sales_invoice' => 'Invoice',
	'sales_creditNote' => 'Retur Credit Note',
	'sales_komisiCustomer' => 'Komisi Customer',
	'sales_komisiSales' => 'Komisi Sales',
	'sales_agingPiutang' => 'Set Aging Piutang',

	'master_account' => 'Account',
	'master_accountClassification' => 'Account Classification',
	'master_accountList' => 'Account List',
	'master_barang' => 'Barang',
	'master_budgetCost' => 'Budget Cost',
	'master_contactPerson' => 'Contact Person',
//	'master_currency' => 'Currency',
	'master_customer' => 'Customer',
	'master_customerGroup' => 'Customer Group',
	'master_customerTipe' => 'Customer Tipe',
	'master_grupsuplier' => 'Grup Supplier',
	'master_gudang' => 'Gudang',
	'master_jenisfakturpajak' => 'Jenis Faktur Pajak',
	'master_jurnal' => 'Jurnal',
	'master_jurnalkodeAccount' => 'Jurnal Kode Account',
	'master_kategoribarang' => 'Kategori Barang',
	'master_kendaraan' => 'Kendaraan',
	'master_kurir' => 'Kurir',
	'master_kurs' => 'Kurs',
	'master_matauang' => 'Mata Uang',
	'master_periodeLaporan' => 'Periode Laporan',
	'master_saldo' => 'Saldo',
	'master_sales' => 'Sales',
	'master_satuanbarang' => 'Satuan Barang',
	'master_suplier' => 'Supplier',
	'master_typeAccount' => 'Type Account',
	'master_typePajak' => 'Type Pajak',
	'master_warehouse' => 'Warehouse',

    'myuser_user' => 'User',
    'myuser_message' => 'Message',
    'myuser_group' => 'Group',
);
$config['actionList'] = array(
	'purchasing_purchaseOrder_view' => 'Lihat',
	'purchasing_purchaseOrder_add' => 'Tambah',
	'purchasing_purchaseOrder_edit' => 'Ubah',
	'purchasing_purchaseOrder_detail' => 'Detail',
	'purchasing_purchaseOrder_report' => 'Report',

	'purchasing_invoice_view' => 'Lihat',
	'purchasing_invoice_add' => 'Tambah',
	'purchasing_invoice_edit' => 'Ubah',
	'purchasing_invoice_detail' => 'Detail',
	
	'purchasing_barangDiterima_view' => 'Lihat',
	'purchasing_barangDiterima_addPO' => 'Tambah',
	'purchasing_barangDiterima_inputPO' => 'Cek PO',
	'purchasing_barangDiterima_edit' => 'Ubah',
//    'purchasing_barangDiterima_detail' => 'Detail',	

	'purchasing_purchasingDebitNote_view' => 'Lihat',
	'purchasing_purchasingDebitNote_edit' => 'Ubah',
	'purchasing_purchasingDebitNote_report' => 'Report',

	'purchasing_agingUtang_view' => 'Lihat',
	'purchasing_agingUtang_add' => 'Tambah',
	'purchasing_agingUtang_edit' => 'Ubah',
//    'purchasing_agingUtang_detail' => 'Detail',
	
	'inventory_persediaan_view' => 'Lihat',
	'inventory_persediaan_add' => 'Tambah',
	'inventory_persediaan_delete' => 'Hapus',

	'inventory_inventorySummary_view' => 'Lihat',
	'inventory_inventorySummary_add' => 'Report',

	'inventory_stockAdjustment_view' => 'Lihat',
	'inventory_stockAdjustment_add' => 'Tambah',

	'inventory_transferGudang_view' => 'Lihat',
	'inventory_transferGudang_addTransfer' => 'Tambah',

	'inventory_inventoryDebitNote_view' => 'Lihat',
	'inventory_inventoryDebitNote_cek' => 'Cek',
	'inventory_inventoryDebitNote_add' => 'Tambah',
	'inventory_inventoryDebitNote_detail' => 'Detail',

	'finance_asset_view' => 'Lihat',
	'finance_asset_add' => 'Tambah',
	'finance_asset_edit' => 'Ubah',
	
	'finance_budgetCost_view' => 'Lihat',
	'finance_budgetCost_add' => 'Tambah',
	'finance_budgetCost_edit' => 'Ubah',
	
	'finance_budgetPurchasing_view' => 'Lihat',
	'finance_budgetPurchasing_add' => 'Tambah',
	'finance_budgetPurchasing_edit' => 'Ubah',

	'finance_bukuBesar_view' => 'Lihat',
	'finance_bukuBesar_add' => 'Tambah',
	'finance_bukuBesar_edit' => 'Ubah',

	'finance_cekGiro_view' => 'Lihat',
	'finance_cekGiro_add' => 'Tambah',
	'finance_cekGiro_edit' => 'Ubah',

	'finance_currentSaldo_view' => 'Lihat',
	'finance_currentSaldo_add' => 'Tambah',
	'finance_currentSaldo_edit' => 'Ubah',

	'finance_fakturPajakCustomer_view' => 'Lihat',
	'finance_fakturPajakCustomer_add' => 'Tambah',
	'finance_fakturPajakCustomer_edit' => 'Ubah',
	'finance_fakturPajakCustomer_detail' => 'Detail',

	'finance_fakturPajakSuplier_view' => 'Lihat',
	'finance_fakturPajakSuplier_add' => 'Tambah',
	'finance_fakturPajakSuplier_edit' => 'Ubah',
	'finance_fakturPajakSuplier_detail' => 'Detail',

	'finance_returFakturCustomer_view' => 'Lihat',
	'finance_returFakturCustomer_add' => 'Tambah',
	'finance_returFakturCustomer_edit' => 'Ubah',
	'finance_returFakturCustomer_detail' => 'Detail',

	'finance_returFakturSuplier_view' => 'Lihat',
	'finance_returFakturSuplier_add' => 'Tambah',
	'finance_returFakturSuplier_edit' => 'Ubah',
	'finance_returFakturSuplier_detail' => 'Detail',

	'finance_hpp_view' => 'Lihat',
	'finance_hpp_add' => 'Tambah',
	'finance_hpp_edit' => 'Ubah',
	'finance_hpp_detail' => 'Detail',

	'finance_jurnal_view' => 'Lihat',
	'finance_jurnal_add' => 'Tambah',
	'finance_jurnal_edit' => 'Ubah',
	'finance_jurnal_detail' => 'Detail',

	'finance_jurnalPenyesuaian_view' => 'Lihat',
	'finance_jurnalPenyesuaian_add' => 'Tambah',
	'finance_jurnalPenyesuaian_edit' => 'Ubah',
	'finance_jurnalPenyesuaian_detail' => 'Detail',

	'finance_kasBank_view' => 'Lihat',
	'finance_kasBank_add' => 'Tambah',
	'finance_kasBank_edit' => 'Ubah',
	'finance_kasBank_detail' => 'Detail',

	'finance_laporanKasBank_view' => 'Lihat',
	'finance_laporanKasBank_add' => 'Tambah',
	'finance_laporanKasBank_edit' => 'Ubah',
	'finance_laporanKasBank_detail' => 'Detail',

	'finance_laporanKeuangan_view' => 'Lihat',
	'finance_laporanKeuangan_add' => 'Tambah',
	'finance_laporanKeuangan_edit' => 'Ubah',
	'finance_laporanKeuangan_detail' => 'Detail',

	'finance_laporanNeraca_view' => 'Lihat',
	'finance_laporanNeraca_add' => 'Tambah',
	'finance_laporanNeraca_edit' => 'Ubah',
	'finance_laporanNeraca_detail' => 'Detail',

	'finance_mutasi_view' => 'Lihat',
	'finance_mutasi_add' => 'Tambah',
	'finance_mutasi_edit' => 'Ubah',
	'finance_mutasi_detail' => 'Detail',
	
	'finance_neraca_view' => 'Lihat',
	'finance_neraca_add' => 'Tambah',
	'finance_neraca_edit' => 'Ubah',
	'finance_neraca_detail' => 'Detail',

	'finance_neracaLajur_view' => 'Lihat',
	'finance_neracaLajur_add' => 'Tambah',
	'finance_neracaLajur_edit' => 'Ubah',
	'finance_neracaLajur_detail' => 'Detail',
	
	'finance_pembayaranHutang_view' => 'Lihat',
	'finance_pembayaranHutang_add' => 'Tambah',
	'finance_pembayaranHutang_edit' => 'Ubah',
	'finance_pembayaranHutang_detail' => 'Detail',

	'finance_penagihanPiutang_view' => 'Lihat',
	'finance_penagihanPiutang_add' => 'Tambah',
	'finance_penagihanPiutang_edit' => 'Ubah',
	'finance_penagihanPiutang_detail' => 'Detail',

	'finance_penerimaanPiutang_view' => 'Lihat',
	'finance_penerimaanPiutang_add' => 'Tambah',
	'finance_penerimaanPiutang_edit' => 'Ubah',
	'finance_penerimaanPiutang_detail' => 'Detail',

	'finance_pengeluarankasBank_view' => 'Lihat',
	'finance_pengeluarankasBank_add' => 'Tambah',
	'finance_pengeluarankasBank_edit' => 'Ubah',
	'finance_pengeluarankasBank_detail' => 'Detail',

	'finance_penyesuaianHutang_view' => 'Lihat',
	'finance_penyesuaianHutang_add' => 'Tambah',
	'finance_penyesuaianHutang_edit' => 'Ubah',
	'finance_penyesuaianHutang_detail' => 'Detail',

	'finance_penyesuaianPiutang_view' => 'Lihat',
	'finance_penyesuaianPiutang_add' => 'Tambah',
	'finance_penyesuaianPiutang_edit' => 'Ubah',
	'finance_penyesuaianPiutang_detail' => 'Detail',

	'finance_perubahanModal_view' => 'Lihat',
	'finance_perubahanModal_add' => 'Tambah',
	'finance_perubahanModal_edit' => 'Ubah',
	'finance_perubahanModal_detail' => 'Detail',

	'finance_receiveMoney_view' => 'Lihat',
	'finance_receiveMoney_add' => 'Tambah',
	'finance_receiveMoney_edit' => 'Ubah',
	'finance_receiveMoney_detail' => 'Detail',

	'finance_report_view' => 'Lihat',
	'finance_report_add' => 'Tambah',
	'finance_report_edit' => 'Ubah',
	'finance_report_detail' => 'Detail',

	'finance_spendMoney_view' => 'Lihat',
	'finance_spendMoney_add' => 'Tambah',
	'finance_spendMoney_edit' => 'Ubah',
	'finance_spendMoney_detail' => 'Detail',

	'finance_transaksi_view' => 'Lihat',
	'finance_transaksi_add' => 'Tambah',
	'finance_transaksi_edit' => 'Ubah',
	'finance_transaksi_detail' => 'Detail',

	'finance_transaksiCustomer_view' => 'Lihat',
	'finance_transaksiCustomer_add' => 'Tambah',
	'finance_transaksiCustomer_edit' => 'Ubah',
	'finance_transaksiCustomer_detail' => 'Detail',

	'sales_penawaran_view' => 'Lihat',
	'sales_penawaran_add' => 'Tambah',
	'sales_penawaran_edit' => 'Ubah',
	'sales_penawaran_detail' => 'Detail',
	'sales_penawaran_report' => 'Report',

	'sales_poCustomer_view' => 'Lihat',
	'sales_poCustomer_add' => 'Tambah',
	'sales_poCustomer_edit' => 'Ubah',
	'sales_poCustomer_detail' => 'Detail',
//	'sales_poCustomer_report' => 'Report',
	
	'sales_suratJalan_view' => 'Lihat',
	'sales_suratJalan_add' => 'Tambah',
	'sales_suratJalan_edit' => 'Ubah',
	'sales_suratJalan_detail' => 'Detail',
	'sales_suratJalan_report' => 'Report',

	'sales_invoice_view' => 'Lihat',
	'sales_invoice_add' => 'Tambah',
	'sales_invoice_edit' => 'Ubah',
	'sales_invoice_detail' => 'Detail',
	'sales_invoice_report' => 'Report',
	
	'sales_creditNote_view' => 'Lihat',
	'sales_creditNote_add' => 'Tambah',
	'sales_creditNote_edit' => 'Ubah',
	'sales_creditNote_detail' => 'Detail',
	'sales_creditNote_report' => 'Report',

	'sales_komisiCustomer_view' => 'Lihat',
	'sales_komisiCustomer_add' => 'Tambah',
	'sales_komisiCustomer_edit' => 'Ubah',
	'sales_komisiCustomer_detail' => 'Detail',
	'sales_komisiCustomer_report' => 'Report',

	'sales_komisiSales_view' => 'Lihat',
	'sales_komisiSales_add' => 'Tambah',
	'sales_komisiSales_edit' => 'Ubah',
	'sales_komisiSales_detail' => 'Detail',
	'sales_komisiSales_report' => 'Report',

	'sales_agingPiutang_view' => 'Lihat',
	'sales_agingPiutang_add' => 'Tambah',
	'sales_agingPiutang_edit' => 'Ubah',

	'master_account_view' => 'Lihat',
	'master_account_add' => 'Tambah',
	'master_account_edit' => 'Ubah',
	'master_account_detail' => 'Detail',
	
	'master_accountClassification_view' => 'Lihat',
	'master_accountClassification_add' => 'Tambah',
	'master_accountClassification_edit' => 'Ubah',
	'master_accountClassification_detail' => 'Detail',

	'master_accountList_view' => 'Lihat',
	'master_accountList_add' => 'Tambah',
	'master_accountList_edit' => 'Ubah',
	'master_accountList_detail' => 'Detail',

	'master_barang_view' => 'Lihat',
	'master_barang_pilihanAdd' => 'Tambah',
	'master_barang_edit' => 'Ubah',
	'master_barang_detail' => 'Detail',

	'master_budgetCost_view' => 'Lihat',
	'master_budgetCost_add' => 'Tambah',
	'master_budgetCost_edit' => 'Ubah',
	'master_budgetCost_detail' => 'Detail',

	'master_contactPerson_view' => 'Lihat',
	'master_contactPerson_add' => 'Tambah',
	'master_contactPerson_edit' => 'Ubah',
	'master_contactPerson_detail' => 'Detail',

	'master_customer_view' => 'Lihat',
	'master_customer_add' => 'Tambah',
	'master_customer_edit' => 'Ubah',
	'master_customer_detail' => 'Detail',

	'master_customerGroup_view' => 'Lihat',
	'master_customerGroup_add' => 'Tambah',
	'master_customerGroup_edit' => 'Ubah',
	'master_customerGroup_detail' => 'Detail',

	'master_customerTipe_view' => 'Lihat',
	'master_customerTipe_add' => 'Tambah',
	'master_customerTipe_edit' => 'Ubah',
	'master_customerTipe_detail' => 'Detail',

	'master_grupsuplier_view' => 'Lihat',
	'master_grupsuplier_add' => 'Tambah',
	'master_grupsuplier_edit' => 'Ubah',
	'master_grupsuplier_detail' => 'Detail',

	'master_gudang_view' => 'Lihat',
	'master_gudang_add' => 'Tambah',
	'master_gudang_edit' => 'Ubah',
	'master_gudang_detail' => 'Detail',

	'master_jenisfakturpajak_view' => 'Lihat',
	'master_jenisfakturpajak_add' => 'Tambah',
	'master_jenisfakturpajak_edit' => 'Ubah',
	'master_jenisfakturpajak_detail' => 'Detail',

	'master_jurnal_view' => 'Lihat',
	'master_jurnal_add' => 'Tambah',
	'master_jurnal_edit' => 'Ubah',
	'master_jurnal_detail' => 'Detail',
	
	'master_jurnalkodeAccount_view' => 'Lihat',
	'master_jurnalkodeAccount_add' => 'Tambah',
	'master_jurnalkodeAccount_edit' => 'Ubah',
	'master_jurnalkodeAccount_detail' => 'Detail',

	'master_kategoribarang_view' => 'Lihat',
	'master_kategoribarang_add' => 'Tambah',
	'master_kategoribarang_edit' => 'Ubah',
	'master_kategoribarang_detail' => 'Detail',

	'master_kendaraan_view' => 'Lihat',
	'master_kendaraan_add' => 'Tambah',
	'master_kendaraan_edit' => 'Ubah',
	'master_kendaraan_detail' => 'Detail',

	'master_kurir_view' => 'Lihat',
	'master_kurir_add' => 'Tambah',
	'master_kurir_edit' => 'Ubah',
	'master_kurir_detail' => 'Detail',

	'master_kurs_view' => 'Lihat',
	'master_kurs_add' => 'Tambah',
	'master_kurs_edit' => 'Ubah',
	'master_kurs_detail' => 'Detail',

	'master_matauang_view' => 'Lihat',
	'master_matauang_add' => 'Tambah',
	'master_matauang_edit' => 'Ubah',
	'master_matauang_detail' => 'Detail',

	'master_periodeLaporan_view' => 'Lihat',
	'master_periodeLaporan_add' => 'Tambah',
	'master_periodeLaporan_edit' => 'Ubah',
	'master_periodeLaporan_detail' => 'Detail',

	'master_saldo_view' => 'Lihat',
	'master_saldo_add' => 'Tambah',
	'master_saldo_edit' => 'Ubah',
	'master_saldo_detail' => 'Detail',
	
	'master_sales_view' => 'Lihat',
	'master_sales_add' => 'Tambah',
	'master_sales_edit' => 'Ubah',
	'master_sales_detail' => 'Detail',

	'master_satuanbarang_view' => 'Lihat',
	'master_satuanbarang_add' => 'Tambah',
	'master_satuanbarang_edit' => 'Ubah',
	'master_satuanbarang_detail' => 'Detail',

	'master_suplier_view' => 'Lihat',
	'master_suplier_add' => 'Tambah',
	'master_suplier_edit' => 'Ubah',
	'master_suplier_detail' => 'Detail',

	'master_typeAccount_view' => 'Lihat',
	'master_typeAccount_add' => 'Tambah',
	'master_typeAccount_edit' => 'Ubah',
	'master_typeAccount_detail' => 'Detail',

	'master_typePajak_view' => 'Lihat',
	'master_typePajak_add' => 'Tambah',
	'master_typePajak_edit' => 'Ubah',
	'master_typePajak_detail' => 'Detail',

	'master_warehouse_view' => 'Lihat',
	'master_warehouse_add' => 'Tambah',
	'master_warehouse_edit' => 'Ubah',
	'master_warehouse_detail' => 'Detail',
		
	'myuser_message_view' => 'Lihat',
	'myuser_message_add' => 'Tambah',
	'myuser_message_reply' => 'Reply',
	'myuser_message_delete' => 'Hapus',

	'myuser_user_access' => 'Hak Akses',
	'myuser_user_add' => 'Tambah',
	'myuser_user_edit' => 'Ubah',
	'myuser_user_delete' => 'Hapus',
	'myuser_user_view' => 'Lihat',
	'myuser_user_status' => 'Status',
	'myuser_user_detail' => 'Detail',
	'myuser_user_resetpasswd' => 'Reset Password',
	'myuser_user_location' => 'Lokasi',
	'myuser_user_accesslocation' => 'Akses Lokasi',

	'myuser_group_add' => 'Tambah',
	'myuser_group_edit' => 'Ubah',
	'myuser_group_delete' => 'Hapus',
	'myuser_group_view' => 'Lihat',
	'myuser_group_detail' => 'Detail',
	'myuser_group_access' => 'Hak Akses',

);

